---
all:
  children:
    webservers:
      hosts:
        staging-web01.example.com:
    databases:
      hosts:
        staging-db01.example.com:
    appservers:
      hosts:
        staging-app01.example.com:
  vars:
    ansible_user: admin
    ansible_port: "{{ ssh_port | default(2222) }}"
