---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
driver:
  name: docker
platforms:
  - name: webserver-debian12
    image: debian:12
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 3600; done"
    privileged: true
  - name: webserver-ubuntu2204
    image: ubuntu:22.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 3600; done"
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: testinfra
